# Generated by Django 4.2.3 on 2024-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_famiya', models.CharField(max_length=200)),
                ('mamlakati', models.CharField(max_length=200)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='rasm/')),
                ('uversitet', models.CharField(max_length=200)),
            ],
        ),
    ]
