# Generated by Django 4.2.3 on 2024-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sponsr_sumpermision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel_raqam', models.IntegerField()),
                ('alliation', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('key_words', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=100)),
                ('fils', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
