# Generated by Django 4.2.3 on 2024-06-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_maqola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqola',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
